# Generated by Django 4.0.3 on 2022-03-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='img',
            field=models.ImageField(default='https://i.postimg.cc/vmM1Hnrc/books.jpg', upload_to='app/uploads/faculties/subjects/images'),
        ),
    ]
