# Generated by Django 4.0.3 on 2022-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='img',
            field=models.TextField(default='https://i.postimg.cc/vmM1Hnrc/books.jpg'),
        ),
    ]
